# JSON Patch (RFC 6902) for ConfigMap/argocd-rbac-cm
- op: add
  path: /metadata/labels/app.kubernetes.io~1name
  value: argocd-rbac-cm
- op: add
  path: /metadata/labels/app.kubernetes.io~1part-of
  value: argocd
- op: add
  path: /data
  value: {}
- op: add
  path: /data/policy.default
  value: role:admin
