image:
  registry: docker.io
  repository: bitnamilegacy/keycloak
  pullPolicy: IfNotPresent

auth:
  adminUser: admin
  existingSecret: keycloak-admin-credentials
  passwordSecretKey: KEYCLOAK_ADMIN_PASSWORD

proxyHeaders: xforwarded
httpEnabled: true

production: false

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
    pullPolicy: IfNotPresent
  auth:
    username: keycloak
    database: keycloak
    existingSecret: keycloak-postgresql-auth
    secretKeys:
      adminPasswordKey: postgres-password
      userPasswordKey: password
  primary:
    persistence:
      enabled: true
      size: 8Gi

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: keycloak.dev.threesixty.dev
  path: /
  pathType: Prefix
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls: true

adminIngress:
  enabled: true
  ingressClassName: nginx
  hostname: keycloak-admin.dev.threesixty.dev
  path: /
  pathType: Prefix
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls: true

